# Generated by Django 4.2.7 on 2023-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('cancelled', 'Скасоване')], default='active', max_length=10),
        ),
    ]
